routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('email-login');
});
Auth::routes(['register' => false]);
// Route::get('/home', 'HomeController@index')->name('home');
Route::view('/email-login', 'email-login')->name('login.email');
// Route::view('/faq', 'faq')->name('faq');

// Route::view('/email-login-dash', 'email-login-dash')->name('login.email.dash');
Route::view('/registrasi', 'registrasi');
//REGISTRASI EMAIL
Route::resource('/email', 'RegisterEmailController');

//ROUTE ADMINISTRATOR
Route::middleware('auth')->group(function () {
    Route::resource('/users', 'UsersController');
});
Route::middleware('auth')->prefix('backend')->group(function () {
    Route::get('/daftar-email', 'Backend\EmailController@index')->name('backend.daftar-email');
});
//ROUTE SINKRON
Route::prefix('sinkron')->group(function () {
    Route::post('/login-email', 'RegisterEmailController@preAuth')->name('sinkron.login');
    //DEVELOP ONLY
    // Route::get('/auth', 'SinkronController@loginMail')->name('sinkron.auth');
    // Route::get('/auth-user', 'SinkronController@loginUserMail')->name('sinkron.user.auth');
    // Route::get('/create-account', 'SinkronController@createAccountEmail')->name('sinkron.create.account');
    // Route::get('/preauth', 'SinkronController@preAuth')->name('sinkron.preauth');

});
//UNUSER ROUTE
// Route::get('/email', 'RegisterEmailController@index');
// Route::get('/emailnon', 'RegisterEmailController@index');
// Route::view('/email-login2', 'email-login2');
// Route::resource('/unit', 'MasterUnitController')->middleware('auth');

resources/views/layout/head.blade.php
<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu navbar-fixed navbar-shadow navbar-brand-center">
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="navbar-collapse" id="navbar-mobile">
                <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                    <ul class="nav navbar-nav">
                        <li class="nav-item mobile-menu d-xl-none mr-auto"><a
                                class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                                    class="ficon feather icon-menu"></i></a></li>
                    </ul>
                </div>
                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link"
                            href="#" data-toggle="dropdown">
                            <div class="user-nav d-sm-flex d-none"><span class="user-name text-bold-600">{{ Auth::user()->name }}</span><span class="user-status">{{ Auth::user()->email }}</span></div><span class="feather icon-user"></span>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/layout/index.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description"
        content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
        content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Pemkab Jombang</title>
    <link rel="apple-touch-icon" href="{{ url ( 'app-assets/images/ico/apple-icon-120.png')}}">
    <link rel="shortcut icon" type="image/x-icon" href="{{ url ( 'app-assets/images/ico/favicon.ico')}}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/vendors/css/vendors.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/vendors/css/charts/apexcharts.css')}}">
    <link rel="stylesheet" type="text/css"
        href="{{ url ( 'app-assets/vendors/css/extensions/tether-theme-arrows.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/vendors/css/extensions/tether.min.css')}}">
    <link rel="stylesheet" type="text/css"
        href="{{ url ( 'app-assets/vendors/css/extensions/shepherd-theme-default.css')}}">
    @stack('css-vendor')
    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/bootstrap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/bootstrap-extended.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/colors.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/components.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/themes/dark-layout.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/themes/semi-dark-layout.css')}}">
    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/core/menu/menu-types/horizontal-menu.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/core/colors/palette-gradient.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/pages/dashboard-analytics.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/pages/card-analytics.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/plugins/tour/tour.css')}}">
    @stack('css-page')
    <!-- END: Page CSS-->
    <!-- BEGIN: Custom CSS-->
    {{-- <link rel="stylesheet" type="text/css" href="{{ url ( 'assets/css/style.css')}}"> --}}
    <!-- END: Custom CSS-->
</head>
<style>
    .horizontal-menu.navbar-floating:not(.blank-page) .registrasi-padding{
        padding-top: 4.0rem;
    }
</style>
<!-- END: Head-->
<!-- BEGIN: Body-->
<body class="horizontal-layout horizontal-menu 2-columns  navbar-floating footer-static" data-open="hover"
    data-menu="horizontal-menu" data-col="2-columns">
    <!-- BEGIN: Header-->
    @auth
        @include('layout.head')
    <!-- END: Header-->
    <!-- BEGIN: Main Menu-->
    <div class="horizontal-menu-wrapper">
        @include('layout.menu')
    </div>
    @endauth
    <!-- END: Main Menu-->
    <!-- BEGIN: Content-->
    <div class="@if(Auth::check()) app-content @else registrasi-padding @endif content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            @yield('content')
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light navbar-shadow">
        <p class="clearfix blue-grey lighten-2 mb-0"><span
                class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT &copy; 2021<a
                    class="text-bold-800 grey darken-2" href="#" target="_blank">Pemerintah Daerah Kabupaten
                    Jombang,</a>All rights Reserved</span>
        </p>
    </footer>
    <!-- END: Footer-->
    <!-- BEGIN: Vendor JS-->
    <script src="{{ url ( 'app-assets/vendors/js/vendors.min.js')}}"></script>
    <!-- BEGIN Vendor JS-->
    <!-- BEGIN: Page Vendor JS-->
    {{-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script> --}}
    <script src="{{ url ( 'app-assets/vendors/js/ui/jquery.sticky.js')}}"></script>
    <script src="{{ url ( 'app-assets/vendors/js/charts/apexcharts.min.js')}}"></script>
    <script src="{{ url ( 'app-assets/vendors/js/extensions/tether.min.js')}}"></script>
    <script src="{{ url ( 'app-assets/vendors/js/extensions/shepherd.min.js')}}"></script>
    @stack('js-vendor')
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="{{ url ( 'app-assets/js/core/app-menu.js')}}"></script>
    <script src="{{ url ( 'app-assets/js/core/app.js')}}"></script>
    <script src="{{ url ( 'app-assets/js/scripts/components.js')}}"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    {{-- <script src="{{ url ( 'app-assets/js/scripts/pages/dashboard-analytics.js')}}"></script> --}}
    @stack('js-page')
    <!-- END: Page JS-->

</body>
<!-- END: Body-->
</html>

resources/views/layout/index2.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description"
        content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
        content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Pemkab Jombang</title>
    <link rel="apple-touch-icon" href="{{ url ( 'app-assets/images/ico/apple-icon-120.png')}}">
    <link rel="shortcut icon" type="image/x-icon" href="{{ url ( 'app-assets/images/ico/favicon.ico')}}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/vendors/css/vendors.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/vendors/css/charts/apexcharts.css')}}">
    <link rel="stylesheet" type="text/css"
        href="{{ url ( 'app-assets/vendors/css/extensions/tether-theme-arrows.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/vendors/css/extensions/tether.min.css')}}">
    <link rel="stylesheet" type="text/css"
        href="{{ url ( 'app-assets/vendors/css/extensions/shepherd-theme-default.css')}}">
    @stack('css-vendor')
    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/bootstrap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/bootstrap-extended.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/colors.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/components.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/themes/dark-layout.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/themes/semi-dark-layout.css')}}">
    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/core/menu/menu-types/horizontal-menu.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/core/colors/palette-gradient.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/pages/dashboard-analytics.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/pages/card-analytics.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url ( 'app-assets/css/plugins/tour/tour.css')}}">
    @stack('css-page')
    <!-- END: Page CSS-->
    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url ( 'assets/css/style.css')}}">
    <!-- END: Custom CSS-->
</head>
<style>
    .registrasi-padding{
        padding-top: 4.0rem;
    }
</style>
<!-- END: Head-->
<!-- BEGIN: Body-->
<body class="horizontal-layout horizontal-menu 2-columns  navbar-floating footer-static" data-open="hover"
    data-menu="horizontal-menu" data-col="2-columns">
    <!-- BEGIN: Header-->
    @auth
        @include('layout.head')
    <!-- END: Header-->
    <!-- BEGIN: Main Menu-->
    <div class="horizontal-menu-wrapper">
        @include('layout.menu')
    </div>
    @endauth
    <!-- END: Main Menu-->
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            @yield('content')
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light navbar-shadow">
        <p class="clearfix blue-grey lighten-2 mb-0"><span
                class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT &copy; 2021<a
                    class="text-bold-800 grey darken-2" href="#" target="_blank">Pemerintah Daerah Kabupaten
                    Jombang,</a>All rights Reserved</span>
        </p>
    </footer>
    <!-- END: Footer-->
    <!-- BEGIN: Vendor JS-->
    <script src="{{ url ( 'app-assets/vendors/js/vendors.min.js')}}"></script>
    <!-- BEGIN Vendor JS-->
    <!-- BEGIN: Page Vendor JS-->
    {{-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script> --}}
    <script src="{{ url ( 'app-assets/vendors/js/ui/jquery.sticky.js')}}"></script>
    <script src="{{ url ( 'app-assets/vendors/js/charts/apexcharts.min.js')}}"></script>
    <script src="{{ url ( 'app-assets/vendors/js/extensions/tether.min.js')}}"></script>
    <script src="{{ url ( 'app-assets/vendors/js/extensions/shepherd.min.js')}}"></script>
    @stack('js-vendor')
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="{{ url ( 'app-assets/js/core/app-menu.js')}}"></script>
    <script src="{{ url ( 'app-assets/js/core/app.js')}}"></script>
    <script src="{{ url ( 'app-assets/js/scripts/components.js')}}"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    {{-- <script src="{{ url ( 'app-assets/js/scripts/pages/dashboard-analytics.js')}}"></script> --}}
    @stack('js-page')
    <!-- END: Page JS-->

</body>
<!-- END: Body-->
</html>

resources/views/layout/menu.blade.php
<div class="header-navbar navbar-expand-sm navbar navbar-horizontal floating-nav navbar-light navbar-without-dd-arrow navbar-shadow menu-border"
    top="" role="navigation" data-menu="menu-wrapper">
    <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item mr-auto"><a class="navbar-brand"
                    href="{{ url ('html/ltr/horizontal-menu-template/index.html')}}">
                    <div class="brand-logo"></div>
                    <h2 class="brand-text mb-0">Jombang</h2>
                </a></li>
            <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i
                        class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i><i
                        class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block collapse-toggle-icon primary"
                        data-ticon="icon-disc"></i></a></li>
        </ul>
    </div>
    <!-- Horizontal menu content-->
    <div class="navbar-container main-menu-content" data-menu="menu-container">
        <!-- include ../../../includes/mixins-->
        <ul class="nav navbar-nav " id="main-menu-navigation" data-menu="menu-navigation">
            @auth
            <li class="{{ Request::is('email')?'active':''}}"><a href="{{url ('email')}}"><i
                        class="feather icon-mail"></i><span data-i18n="Apps">Daftar Email</span></a>
            </li>
            @endauth
            <li class="{{ Request::is('email-login')?'active':''}}"><a href="{{url ('email-login')}}"><i
                class="feather icon-lock"></i><span data-i18n="Others">Login Email</span></a>

    </li>
            @guest
                
            @endguest
            
            @auth
                <li class="{{ Request::is('users')?'active':''}}"><a href="{{route('users.index')}}"><i
                            class="feather icon-users"></i><span data-i18n="Others">User</span></a>
                </li>
            <li style="position: absolute !important;
            right: 0;
            top: 0;"><a href="{{ route('logout') }}" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();"><i class="feather icon-log-out"></i><span
                        data-i18n="Pages">Logout</span></a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </li>
            @endauth

        </ul>
    </div>
</div>