routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('email-login');
});
Auth::routes(['register' => false]);
// Route::get('/home', 'HomeController@index')->name('home');
Route::view('/email-login', 'email-login')->name('login.email');
// Route::view('/faq', 'faq')->name('faq');

// Route::view('/email-login-dash', 'email-login-dash')->name('login.email.dash');
Route::view('/registrasi', 'registrasi');
//REGISTRASI EMAIL
Route::resource('/email', 'RegisterEmailController');

//ROUTE ADMINISTRATOR
Route::middleware('auth')->group(function () {
    Route::resource('/users', 'UsersController');
});
Route::middleware('auth')->prefix('backend')->group(function () {
    Route::get('/daftar-email', 'Backend\EmailController@index')->name('backend.daftar-email');
});
//ROUTE SINKRON
Route::prefix('sinkron')->group(function () {
    Route::post('/login-email', 'RegisterEmailController@preAuth')->name('sinkron.login');
    //DEVELOP ONLY
    // Route::get('/auth', 'SinkronController@loginMail')->name('sinkron.auth');
    // Route::get('/auth-user', 'SinkronController@loginUserMail')->name('sinkron.user.auth');
    // Route::get('/create-account', 'SinkronController@createAccountEmail')->name('sinkron.create.account');
    // Route::get('/preauth', 'SinkronController@preAuth')->name('sinkron.preauth');

});
//UNUSER ROUTE
// Route::get('/email', 'RegisterEmailController@index');
// Route::get('/emailnon', 'RegisterEmailController@index');
// Route::view('/email-login2', 'email-login2');
// Route::resource('/unit', 'MasterUnitController')->middleware('auth');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/EmailController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Email;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Log;

class EmailController extends Controller
{
    public function index()
    {
        $email = Email::latest()->get();
        return view('backend.email.index', compact(['email']));

    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User as User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    public function index()
    {
        try {
            $users = User::latest()->get();
        } catch (Exception $th) {
            Log::error($e->getMessage());
        }
        return view('backend.users.index', compact('users'));

    }
    public function create()
    {
        return view('backend.users.add');
    }
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|min:4',
            'email' => 'required|unique:App\User,email|email:rfc,dns|',
            'password' => 'required|min:6',
        ]);
        try {
            $dataInsert = [
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'password'=> Hash::make($request->input('password')),
            ];
            $insert=User::create($dataInsert);
        } catch (\Throwable $th) {
            Log::error($e->getMessage());
            return redirect()->back()->with('error', 'Data tidak tersimpan');
        }
        return redirect()->route('users.index')->with('success', 'Data disimpan');

    }
    public function edit($id)
    {
        try {
            $idUser = $id;
            $user = User::where('id', $idUser)->first();
        } catch (Exception $e) {
            Log::error($e->getMessage());
            return redirect()->back()->with('error', 'Data tidak berubah');
        }
        return view('backend.users.edit', compact('user'));
    }
    public function update(Request $request, $id)
    {
        try {
            $dataUpdated = [
                'name' => $request->input('name'),
                'email' => $request->input('email'),
            ];
            if ($request->input('password')) {
                $dataUpdated['password'] = Hash::make($request->input('password'));
            }
            $update = User::where('id', $id)->update($dataUpdated);
        } catch (Exception $e) {
            Log::error($e->getMessage());
            return redirect()->back()->with('error', 'Data tidak berubah');
        }
        return redirect()->route('users.index')->with('success', 'Data berubah');

    }
    public function destroy($id)
    {
        try {

            $delete=User::where('id',$id)->delete();
        } catch (Exception $e) {
            Log::error($e->getMessage());
            return redirect()->back()->with('error', 'Data tidak terhapus');
        }
        return redirect()->back()->with('success', 'Data dihapus');

    }
}

resources/views/backend/users/add.blade.php
@extends('layout.index')
@push('css-vendor')
@endpush
@push('css-page')
@endpush
@section('content')
<div class="content-body">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">User Admin</h4>
            {{-- <a href="{{ route('email.create')}}" type="submit" class="btn btn-primary mr-1 mb-1">Tambah</a> --}}
        </div>
        <div class="card-content">
            <div class="card-body card-dashboard">
                @if(Session::has('success'))
                <div class="alert alert-success" role="alert">
                    {{ Session('success') }}
                </div>
                @elseif(Session::has('error'))
                <div class="alert alert-success" role="alert">
                    {{ Session('error') }}
                </div>
                @endif
                <form class="form form-horizontal" method="post" action="{{route('users.store')}}">
                    @csrf
                    <div class="form-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <span>Nama</span>
                                    </div>
                                    <div class="col-md-8">
                                        <input type="text" id="first-name" class="form-control @error('name') is-invalid @enderror" name="name"
                                            placeholder="First Name" value="{{old('name')}}">
                                            @error('name')
                                            <div class="invalid-feedback">
                                                    {{$message}}
                                                </div>
                                            @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <span>Email</span>
                                    </div>
                                    <div class="col-md-8">
                                        <input type="email" id="email-id" class="form-control @error('email') is-invalid @enderror"  name="email"
                                            placeholder="Email" value="{{old('email')}}">
                                            @error('email')
                                            <div class="invalid-feedback">
                                                    {{$message}}
                                                </div>
                                            @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <span>Password</span>
                                    </div>
                                    <div class="col-md-8">
                                        <input type="password" id="password" class="form-control @error('password') is-invalid @enderror" name="password"
                                            placeholder="Password" value="{{old('password')}}">
                                            @error('password')
                                            <div class="invalid-feedback">
                                                    {{$message}}
                                                </div>
                                            @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary mr-1 mb-1">Simpan</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js-vendor')
@endpush
@push('js-page')
@endpush

resources/views/backend/users/edit.blade.php
@extends('layout.index')
@push('css-vendor')
@endpush
@push('css-page')
@endpush
@section('content')
<div class="content-body">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">User Admin</h4>
            {{-- <a href="{{ route('email.create')}}" type="submit" class="btn btn-primary mr-1 mb-1">Tambah</a> --}}
        </div>
        <div class="card-content">
            <div class="card-body card-dashboard">
                @if(Session::has('success'))
                <div class="alert alert-success" role="alert">
                    {{ Session('success') }}
                </div>
                @elseif(Session::has('error'))
                <div class="alert alert-success" role="alert">
                    {{ Session('error') }}
                </div>
                @endif
                <form class="form form-horizontal" method="post" action="{{route('users.update',$user->id)}}">
                    @csrf
                    @method('PUT')
                    <div class="form-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <span>Nama</span>
                                    </div>
                                    <div class="col-md-8">
                                        <input type="text" id="first-name" class="form-control" name="name"
                                            placeholder="First Name" value="{{$user->name}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <span>Email</span>
                                    </div>
                                    <div class="col-md-8">
                                        <input type="email" id="email-id" class="form-control" name="email"
                                            placeholder="Email" value="{{$user->email}}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <span>Password</span>
                                    </div>
                                    <div class="col-md-8">
                                        <input type="password" id="password" class="form-control" name="password"
                                            placeholder="Password">
                                            <p><small class="text-muted">Kosongkan jika tidak update password</small></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary mr-1 mb-1">Perbarui</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js-vendor')
@endpush
@push('js-page')
@endpush

resources/views/backend/users/index.blade.php
@extends('layout.index')
@push('css-vendor')
<link rel="stylesheet" type="text/css" href="{{ url ('app-assets/vendors/css/tables/datatable/datatables.min.css')}}">
@endpush
@push('css-page')
<link rel="stylesheet" type="text/css" href="{{url('app-assets/vendors/css/extensions/sweetalert2.min.css')}}">
@endpush
@section('content')
<div class="content-body">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">User Admin</h4>
            {{-- <a href="{{ route('email.create')}}" type="submit" class="btn btn-primary mr-1 mb-1">Tambah</a> --}}
        </div>
        <div class="card-content">
            <div class="card-body card-dashboard">
                @if(Session::has('success'))
                <div class="alert alert-success" role="alert">
                    {{ Session('success') }}
                </div>
                @elseif(Session::has('error'))
                <div class="alert alert-danger" role="alert">
                    {{ Session('error') }}
                </div>
                @endif
                <a href="{{ route('users.create')}}" class="btn btn-primary mr-1 mb-1">Tambah</a>
                <div class="table-responsive">
                    <table class="table nowrap zero-configuration" style="text-align: center">
                        <thead>
                            <tr>
                                <th width="50px">No</th>
                                <th width="200px">Nama</th>
                                <th width="300px">Email</th>
                                <th width="200px">Aksi</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $hasil)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $hasil->name }}</td>
                                <td>{{ $hasil->email }}</td>
                                <td>
                                    <button type="button" data-id={{$hasil->id}}
                                        class="btn btn-icon btn-danger mr-1 mb-1 confirm-alert"><i
                                            class="feather icon-trash"></i></button>
                                    <a href="{{ route('users.edit', $hasil->id ) }}"
                                        class="btn btn-icon btn-warning mr-1 mb-1"><i class="feather icon-edit"></i></a>
                                    <form id="delete{{$hasil->id}}" action="{{ route('users.destroy', $hasil->id )}}"
                                        method="POST">
                                        @csrf
                                        @method('delete')
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{-- {{ $email->links() }} --}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js-vendor')
<script src="{{ url('app-assets/vendors/js/tables/datatable/pdfmake.min.js')}}"></script>
<script src="{{ url('app-assets/vendors/js/tables/datatable/vfs_fonts.js')}}"></script>
<script src="{{ url('app-assets/vendors/js/tables/datatable/datatables.min.js')}}"></script>
<script src="{{ url('app-assets/vendors/js/tables/datatable/datatables.buttons.min.js')}}"></script>
<script src="{{ url('app-assets/vendors/js/tables/datatable/buttons.html5.min.js')}}"></script>
<script src="{{ url('app-assets/vendors/js/tables/datatable/buttons.print.min.js')}}"></script>
<script src="{{ url('app-assets/vendors/js/tables/datatable/buttons.bootstrap.min.js')}}"></script>
<script src="{{ url('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js')}}"></script>
@endpush
@push('js-page')
<script src="{{ url('app-assets/vendors/js/extensions/sweetalert2.all.min.js')}}"></script>
<script src="{{ url('app-assets/vendors/js/my.js')}}"></script>
@endpush